language: bash
services: docker

env:
  - VERSION=2.1 VARIANT=
  - VERSION=2.1 ARCH=i386
  - VERSION=2.1 VARIANT=alpine
  - VERSION=2.0 VARIANT=
  - VERSION=2.0 ARCH=i386
  - VERSION=2.0 VARIANT=alpine
  - VERSION=1.9 VARIANT=
  - VERSION=1.9 ARCH=i386
  - VERSION=1.9 VARIANT=alpine
  - VERSION=1.8 VARIANT=
  - VERSION=1.8 ARCH=i386
  - VERSION=1.8 VARIANT=alpine
  - VERSION=1.7 VARIANT=
  - VERSION=1.7 ARCH=i386
  - VERSION=1.7 VARIANT=alpine
  - VERSION=1.6 VARIANT=
  - VERSION=1.6 ARCH=i386
  - VERSION=1.6 VARIANT=alpine
  - VERSION=1.5 VARIANT=
  - VERSION=1.5 ARCH=i386
  - VERSION=1.5 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION${VARIANT+/$VARIANT}"
  - image="haproxy:${VERSION}${VARIANT+-$VARIANT}"
  - |
    if [ -n "$ARCH" ]; then
        from="$(awk '$1 == toupper("FROM") { print $2 }' Dockerfile)"
        docker pull "$ARCH/$from"
        docker tag "$ARCH/$from" "$from"
    fi

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
